# Kustomization para recursos BASE do orquestrador
# Os manifestos de cada projeto são aplicados via scripts (kubectl apply -f)
# devido a restrições de segurança do Kustomize com paths externos
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  app.kubernetes.io/part-of: fiap-cloud-games
  app.kubernetes.io/managed-by: kustomize


resources:
  - base/namespace.yaml
