apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: fiap-cloud-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1337
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_ADAPTER
          value: "postgres"
        - name: DB_HOST
          value: "postgres-kong"
        - name: DB_USER
          value: "kong"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: password
        - name: DB_DATABASE
          value: "konga"
        - name: DB_PORT
          value: "5432"
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
