apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: fiap-cloud-games
spec:
  type: LoadBalancer
  selector:
    app: konga
  ports:
  - port: 1337
    targetPort: 1337
    protocol: TCP
    name: http
