{
 "title": "FIAP - Throughput e Contagem de Requisições",
 "description": "Dashboard de Throughput e Contagem de Requisições - FIAP Cloud Games",
 "tags": [
  "fiap",
  "throughput",
  "requests"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Throughput - Taxa de Requisições por Segundo",
   "type": "timeseries",
   "description": "Taxa de requisições por segundo em cada serviço",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Requisições por Status Code HTTP",
   "type": "timeseries",
   "description": "Total de requisições por Status HTTP Code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Total de Requisições por Serviço (5 min)",
   "type": "barchart",
   "description": "Contagem total de requisições por serviço (últimas 5 min)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[5m])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Distribuição de Requisições (últimas 5 min)",
   "type": "piechart",
   "description": "Distribuição de requisições por serviço",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[5m])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}