# Secrets para o RabbitMQ
# IMPORTANTE: Armazena dados SENSÍVEIS
# Em produção, use um gerenciador de secrets externo!
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: fiap-cloud-games
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: fiap-cloud-games
type: Opaque
stringData:
  # ATENÇÃO: Substitua essas credenciais em produção!
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "rabbitmq123"
