# Secrets do Grafana
# Credencial do usuário admin (em produção use um gerenciador externo).
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: fiap-cloud-games
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: fiap-cloud-games
type: Opaque
stringData:
  admin-password: "admin"
